// Generated by Gemini Flash 3.5
package vn.io.tozydev.tusu.data

import androidx.room.immediateTransaction
import androidx.room.useWriterConnection
import kotlin.time.Instant
import kotlin.uuid.Uuid
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import vn.io.tozydev.tusu.data.db.EntryEntity
import vn.io.tozydev.tusu.data.db.EntryTagCrossRef
import vn.io.tozydev.tusu.data.db.MediaEntity
import vn.io.tozydev.tusu.data.db.TagEntity
import vn.io.tozydev.tusu.data.db.TusuDatabase

internal object TestData {
    // ============================================================================================
    // 1. TAG IDENTIFIERS (10 Tags)
    // ============================================================================================
    val duLichTagId = Uuid.fromLongs(0, 1)
    val amThucTagId = Uuid.fromLongs(0, 2)
    val thienNhienTagId = Uuid.fromLongs(0, 3)
    val doiSongTagId = Uuid.fromLongs(0, 4)
    val nhiepAnhTagId = Uuid.fromLongs(0, 5)
    val phoCoTagId = Uuid.fromLongs(0, 6)
    val caPheTagId = Uuid.fromLongs(0, 7)
    val tamTrangTagId = Uuid.fromLongs(0, 8)
    val ThoiGianTagId = Uuid.fromLongs(0, 9)
    val suyNghitTagId = Uuid.fromLongs(0, 10)

    // ============================================================================================
    // 2. MEDIA IDENTIFIERS (10 Images)
    // ============================================================================================
    val media1Id = Uuid.fromLongs(0, 101) // pexels-son-hoa-nguyen-2155579462-33908285.jpg
    val media2Id = Uuid.fromLongs(0, 102) // pexels-phuong-tran-163155-9552977.jpg
    val media3Id = Uuid.fromLongs(0, 103) // pexels-l-c-nguy-n-557025598-33413686.jpg
    val media4Id = Uuid.fromLongs(0, 104) // pexels-vubui-30248830.jpg
    val media5Id = Uuid.fromLongs(0, 105) // pexels-son-hoa-nguyen-2155579462-33969966.jpg
    val media6Id = Uuid.fromLongs(0, 106) // pexels-ndtoanf-27454425.jpg
    val media7Id = Uuid.fromLongs(0, 107) // pexels-vubui-30248863.jpg
    val media8Id = Uuid.fromLongs(0, 108) // pexels-son-hoa-nguyen-2155579462-33969968.jpg
    val media9Id = Uuid.fromLongs(0, 109) // pexels-hoanggiahuy-13443167.jpg
    val media10Id = Uuid.fromLongs(0, 110) // 00000000-0000-0000-0000-00000000006e.jpg

    // ============================================================================================
    // 3. ENTRY IDENTIFIERS (10 Entries)
    // ============================================================================================
    val entry1Id = Uuid.fromLongs(0, 1001)
    val entry2Id = Uuid.fromLongs(0, 1002)
    val entry3Id = Uuid.fromLongs(0, 1003)
    val entry4Id = Uuid.fromLongs(0, 1004)
    val entry5Id = Uuid.fromLongs(0, 1005)
    val entry6Id = Uuid.fromLongs(0, 1006)
    val entry7Id = Uuid.fromLongs(0, 1007)
    val entry8Id = Uuid.fromLongs(0, 1008)
    val entry9Id = Uuid.fromLongs(0, 1009)
    val entry10Id = Uuid.fromLongs(0, 1010)

    // ============================================================================================
    // 4. ENTITY LISTS
    // ============================================================================================

    val tags =
        listOf(
            TagEntity(duLichTagId, "Du Lịch"),
            TagEntity(amThucTagId, "Ẩm Thực"),
            TagEntity(thienNhienTagId, "Thiên Nhiên"),
            TagEntity(doiSongTagId, "Đời Sống"),
            TagEntity(nhiepAnhTagId, "Nhiếp Ảnh"),
            TagEntity(phoCoTagId, "Phố Cổ"),
            TagEntity(caPheTagId, "Cà Phê"),
            TagEntity(tamTrangTagId, "Tâm Trạng"),
            TagEntity(ThoiGianTagId, "Thời Gian"),
            TagEntity(suyNghitTagId, "Suy Nghĩ"),
        )

    val media =
        listOf(
            // Thuộc Entry 1 (Phân bổ 5 ảnh: media1 -> media5)
            MediaEntity(
                id = media1Id,
                entryId = entry1Id,
                mimeType = "image/jpeg",
                filename = "pexels-son-hoa-nguyen-2155579462-33908285.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-000000000065.jpg",
                order = 1.0f,
                height = 4000,
                width = 3000,
            ),
            MediaEntity(
                id = media2Id,
                entryId = entry1Id,
                mimeType = "image/jpeg",
                filename = "pexels-phuong-tran-163155-9552977.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-000000000066.jpg",
                order = 2.0f,
                height = 3000,
                width = 4500,
            ),
            MediaEntity(
                id = media3Id,
                entryId = entry1Id,
                mimeType = "image/jpeg",
                filename = "pexels-l-c-nguy-n-557025598-33413686.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-000000000067.jpg",
                order = 3.0f,
                height = 4000,
                width = 2667,
            ),
            MediaEntity(
                id = media4Id,
                entryId = entry1Id,
                mimeType = "image/jpeg",
                filename = "pexels-vubui-30248830.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-000000000068.jpg",
                order = 4.0f,
                height = 3840,
                width = 2160,
            ),
            MediaEntity(
                id = media5Id,
                entryId = entry1Id,
                mimeType = "image/jpeg",
                filename = "pexels-son-hoa-nguyen-2155579462-33969966.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-000000000069.jpg",
                order = 5.0f,
                height = 4000,
                width = 3000,
            ),

            // Thuộc Entry 2 (Phân bổ 3 ảnh: media6 -> media8)
            MediaEntity(
                id = media6Id,
                entryId = entry2Id,
                mimeType = "image/jpeg",
                filename = "pexels-ndtoanf-27454425.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-00000000006a.jpg",
                order = 1.0f,
                height = 4160,
                width = 3120,
            ),
            MediaEntity(
                id = media7Id,
                entryId = entry2Id,
                mimeType = "image/jpeg",
                filename = "pexels-vubui-30248863.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-00000000006b.jpg",
                order = 2.0f,
                height = 3840,
                width = 2160,
            ),
            MediaEntity(
                id = media8Id,
                entryId = entry2Id,
                mimeType = "image/jpeg",
                filename = "pexels-son-hoa-nguyen-2155579462-33969968.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-00000000006c.jpg",
                order = 3.0f,
                height = 4000,
                width = 3000,
            ),

            // Thuộc Entry 3 (Phân bổ 2 ảnh: media9 -> media10)
            MediaEntity(
                id = media9Id,
                entryId = entry3Id,
                mimeType = "image/jpeg",
                filename = "pexels-hoanggiahuy-13443167.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-00000000006d.jpg",
                order = 1.0f,
                height = 2940,
                width = 1960,
            ),
            MediaEntity(
                id = media10Id,
                entryId = entry3Id,
                mimeType = "image/jpeg",
                filename = "00000000-0000-0000-0000-00000000006e.jpg",
                path = "./media/00/00/00000000-0000-0000-0000-00000000006e.jpg",
                order = 2.0f,
                height = 4000,
                width = 2667,
            ),
        )

    val entries =
        listOf(
            // Entry 1: Đầy đủ các thuộc tính (5 ảnh, có emoji, có tag)
            EntryEntity(
                id = entry1Id,
                recordedAt = Instant.parse("2026-06-21T08:00:00Z"),
                emoji = "🏮",
                content =
                    """
                    # Hành trình Khám phá Di sản Miền Trung

                    Hôm nay là một ngày thật tuyệt vời khi được đặt chân đến mảnh đất cố đô cổ kính. Tiết trời mùa hè có chút oi ả nhưng không làm giảm đi sự háo hức trong lòng.

                    ## Những địa điểm đã đi qua:
                    1. **Phố cổ Hội An**: Lung linh sắc đèn lồng về đêm.
                    2. **Đại nội Huế**: Cổ kính, uy nghiêm trầm mặc theo thời gian.
                    3. **Thánh địa Mỹ Sơn**: Những ngọn tháp gạch nung nhuốm màu huyền bí.

                    > "Du lịch không chỉ là ngắm nhìn cảnh vật, mà là sự thay đổi sâu sắc và bền vững trong tư duy về cuộc sống."

                    Trải nghiệm thưởng thức ly *cà phê phin* bên bờ sông Hoài lúc chạng vạng tối mang lại cảm giác vô cùng bình yên.
                    """
                        .trimIndent(),
            ),

            // Entry 2: Đầy đủ các thuộc tính (3 ảnh, có emoji, có tag)
            EntryEntity(
                id = entry2Id,
                recordedAt = Instant.parse("2026-06-20T14:30:00Z"),
                emoji = "☕",
                content =
                    """
                    # Góc Nhỏ Bình Yên Giữa Lòng Thành Phố

                    Tìm được một quán cà phê ẩn mình sâu trong con ngõ nhỏ. Không gian nơi đây tách biệt hoàn toàn với sự xô bồ, náo nhiệt ngoài kia.

                    * Mùi hạt cà phê rang xay thơm nồng.
                    * Tiếng nhạc Jazz nhẹ nhàng, du dương.
                    * Ánh đèn vàng ấm cúng lan tỏa khắp căn phòng.

                    Mình đã dành cả buổi chiều chỉ để đọc nốt cuốn sách còn dang dở và suy ngẫm về những kế hoạch sắp tới. `Năng lượng tích cực` đã được nạp đầy!
                    """
                        .trimIndent(),
            ),

            // Entry 3: Loại chỉ có thông tin bắt buộc + 1 property optional: MEDIA (Có 2 ảnh, KHÔNG
            // emoji, KHÔNG tag)
            EntryEntity(
                id = entry3Id,
                recordedAt = Instant.parse("2026-06-19T06:15:00Z"),
                emoji = null,
                content =
                    """
                    # Bình Minh Trên Biển Vắng

                    Thức dậy từ **5 giờ sáng** để đón những tia nắng đầu tiên. Biển dịu êm, từng đợt sóng nhỏ vỗ nhẹ vào bờ cát mịn màng.

                    Cảnh vật lúc này đẹp như một bức tranh thủy mặc. Tôi đã kịp ghi lại khoảnh khắc bình minh xuất sắc này thông qua ống kính máy ảnh của mình.

                    Hy vọng một ngày mới sẽ ngập tràn may mắn và niềm vui đến với tất cả mọi người.
                    """
                        .trimIndent(),
            ),

            // Entry 4: Loại chỉ có thông tin bắt buộc + 1 property optional: EMOJI (Có emoji, KHÔNG
            // media, KHÔNG tag)
            EntryEntity(
                id = entry4Id,
                recordedAt = Instant.parse("2026-06-18T21:00:00Z"),
                emoji = "🧘",
                content =
                    """
                    # Ngày Sống Chậm Và Chiêm Nghiệm

                    Đôi khi, việc dừng lại một nhịp giữa nhịp sống hối hả là điều vô cùng cần thiết. Hôm nay mình thực hiện thử thách cắt giảm thời gian sử dụng mạng xã hội.

                    - Tập trung vào hơi thở qua bài thiền định 20 phút.
                    - Tự tay nấu một bữa ăn tối đơn giản nhưng đủ chất.
                    - Trò chuyện sâu sắc hơn với những người thân yêu.

                    Kết quả nhận lại thật bất ngờ, tâm trí trở nên thông suốt và bớt âu lo hơn rất nhiều.
                    """
                        .trimIndent(),
            ),

            // Entry 5: Loại chỉ có thông tin bắt buộc + 1 property optional: TAG (Có tag thông qua
            // bảng nối, KHÔNG emoji, KHÔNG media)
            EntryEntity(
                id = entry5Id,
                recordedAt = Instant.parse("2026-06-17T11:00:00Z"),
                emoji = null,
                content =
                    """
                    # Ghi Chép Về Món Ăn Đường Phố Hà Nội

                    Không thể phủ nhận văn hóa ẩm thực đường phố tại đây luôn có một sức hút đặc biệt. Sáng nay dạo quanh khu vực bờ hồ, hương vị của bát bún thang truyền thống làm mình nhớ mãi.

                    **Nước dùng** ngọt thanh từ xương, sợi bún nhỏ kèm theo các loại topping được thái sợi chỉ vô cùng tinh tế. Đúng là đỉnh cao của sự khéo léo!
                    """
                        .trimIndent(),
            ),

            // Entry 6: Không có heading (Trường hợp 1) + Không có emoji, không có media (Chỉ liên
            // kết Tag)
            EntryEntity(
                id = entry6Id,
                recordedAt = Instant.parse("2026-06-16T15:45:00Z"),
                emoji = null,
                content =
                    """
                    Trời bỗng đổ cơn mưa rào bất chợt giữa buổi chiều hè. Ngồi trong văn phòng nhìn từng giọt nước xối xả đập vào ô cửa kính, lòng lại dâng lên những xúc cảm khó tả.

                    Mưa mang đi cái nóng nực của thành thị, nhưng cũng vô tình để lại những khoảng trống trống trải trong suy nghĩ về tương lai và sự nghiệp. Cần cố gắng nhiều hơn nữa!
                    """
                        .trimIndent(),
            ),

            // Entry 7: Không có heading (Trường hợp 2) + Có emoji, không media, không tag
            EntryEntity(
                id = entry7Id,
                recordedAt = Instant.parse("2026-06-15T09:30:00Z"),
                emoji = "🌱",
                content =
                    """
                    Cây mầm nhỏ bé trồng ngoài ban công sau bao ngày chăm sóc cuối cùng cũng đã nhú lên những chiếc lá xanh non đầu tiên.

                    Sức sống của thiên nhiên thật kỳ diệu. Nhìn thấy nó, mình như có thêm động lực để bắt đầu một tuần làm việc mới thật năng suất và hiệu quả. Chúc mọi người tuần mới vui vẻ!
                    """
                        .trimIndent(),
            ),

            // Entry 8: Không có heading (Trường hợp 3) + Có emoji, có tag, không media
            EntryEntity(
                id = entry8Id,
                recordedAt = Instant.parse("2026-06-14T23:59:00Z"),
                emoji = "📅",
                content =
                    """
                    Thêm một tuần nữa trôi qua thật nhanh. Nhìn lại danh sách những việc cần làm (`To-do list`), vẫn còn vài hạng mục chưa hoàn thành dứt điểm.

                    * Cần tối ưu hóa lại quản lý thời gian.
                    * Hạn chế sa đà vào các tác vụ không tên.
                    * Nghiêm túc thực hiện kế hoạch đã đề ra ban đầu.
                    """
                        .trimIndent(),
            ),

            // Entry 9: Chỉ có thông tin bắt buộc duy nhất (KHÔNG emoji, KHÔNG media, KHÔNG tag liên
            // kết)
            EntryEntity(
                id = entry9Id,
                recordedAt = Instant.parse("2026-06-13T12:00:00Z"),
                emoji = null,
                content =
                    """
                    # Nhật Ký Code Dự Án Tusu App

                    Hôm nay hoàn thành việc cấu trúc tầng Data Layer và cài đặt hệ thống cơ sở dữ liệu local sử dụng **Room Database**.

                    Việc xử lý quan hệ nhiều-nhiều (`Many-to-Many`) giữa `EntryEntity` và `TagEntity` qua bảng trung gian tương đối suôn sẻ. Mọi Unit Test cho các hàm DAO đều đã báo xanh pass toàn bộ.
                    """
                        .trimIndent(),
            ),

            // Entry 10: Thêm biến thể phân phối trạng thái (Có emoji, không có heading, không tag,
            // không media)
            EntryEntity(
                id = entry10Id,
                recordedAt = Instant.parse("2026-06-12T18:20:00Z"),
                emoji = "🏃",
                content =
                    """
                    Hoàn thành chặng đường chạy bộ **5km** liên tục quanh công viên mà không nghỉ một phút nào. Kỷ lục cá nhân mới đã được thiết lập!

                    Cảm giác mồ hôi đổ xuống kèm nhịp tim đập mạnh giúp giải phóng toàn bộ stress tích tụ suốt cả tuần qua. Thể dục thể thao đúng là liều thuốc bổ giá trị nhất cho tinh thần.
                    """
                        .trimIndent(),
            ),
        )

    // ============================================================================================
    // 5. CROSS REFERENCE TABLE (Bảng trung gian nối quan hệ Many-to-Many giữa Entry và Tag)
    // ============================================================================================
    val entryTags =
        listOf(
            // Entry 1 có đầy đủ các tags tương ứng nội dung bài viết
            EntryTagCrossRef(entry1Id, duLichTagId),
            EntryTagCrossRef(entry1Id, phoCoTagId),
            EntryTagCrossRef(entry1Id, amThucTagId),

            // Entry 2 liên kết các tag liên quan
            EntryTagCrossRef(entry2Id, caPheTagId),
            EntryTagCrossRef(entry2Id, doiSongTagId),
            EntryTagCrossRef(entry2Id, nhiepAnhTagId),

            // Entry 5 (Loại chỉ có thông tin bắt buộc + 1 thuộc tính Tag)
            EntryTagCrossRef(entry5Id, amThucTagId),

            // Entry 6 (Không heading nhưng vẫn có tag liên quan)
            EntryTagCrossRef(entry6Id, tamTrangTagId),

            // Entry 8 (Không heading có tag thời gian và suy nghĩ)
            EntryTagCrossRef(entry8Id, ThoiGianTagId),
            EntryTagCrossRef(entry8Id, suyNghitTagId),
        )
}

internal suspend fun seedTestData(db: TusuDatabase) {
    db.useWriterConnection {
        it.immediateTransaction {
            if (db.entryDao().getFirstEntryId() != null) {
                return@immediateTransaction
            }
            db.tagDao().insertAll(TestData.tags)
            db.entryDao().insertAll(TestData.entries)
            db.mediaDao().insertAll(TestData.media)
            db.entryTagDao().insertAll(TestData.entryTags)
        }
    }
    withContext(Dispatchers.IO) {
        copyTestMediaToAppDir()
    }
}

internal expect suspend fun copyTestMediaToAppDir()
