name: Release
on:
  workflow_dispatch:
    inputs:
      modifier:
        type: choice
        default: ""
        options:
          - ""
          - "-preview"

      prerelease:
        type: boolean
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.calver-release.outputs.version }}
      tag: ${{ steps.calver-release.outputs.tag }}
    steps:
      - name: CalVer Release
        id: calver-release
        uses: tozydev/gh-actions/calver-release@v1
        with:
          extra-files: gradle.properties
          modifier: ${{ inputs.modifier }}
          prerelease: ${{ inputs.prerelease }}
          app-client-id: ${{ vars.SOHYOL_APP_CLIENT_ID }}
          app-private-key: ${{ secrets.SOHYOL_APP_PRIVATE_KEY }}

  call-build:
    needs: release
    uses: tozydev/gh-actions/.github/workflows/shared-gradle-build.yml@v1
    with:
      checkout-ref: ${{ needs.release.outputs.tag }}
      gradle-args: :app:androidApp:assembleRelease
      upload-artifacts-path: app/androidApp/build/outputs/apk/release/*.apk
      upload-artifacts-name: release-artifacts
    secrets:
      github-token: ${{ github.token }}
      keystore-base64: ${{ secrets.KEYSTORE_BASE64 }}
      env-vars: |
        KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS=${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}

  upload-artifact:
    runs-on: ubuntu-slim
    needs:
      - release
      - call-build
    permissions:
      contents: write
    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v8
        with:
          name: release-artifacts
          path: dist/

      - name: Rename artifact
        run: |
          mv dist/*.apk dist/tusu-${{ needs.release.outputs.version }}.apk

      - name: Upload artifact to GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ needs.release.outputs.tag }} dist/*.apk --repo ${{ github.repository }}
