name: Release
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: CalVer Release
        uses: tozydev/gh-actions/calver-release@main
        with:
          extra-files: gradle.properties
          app-client-id: ${{ vars.SOHYOL_APP_CLIENT_ID }}
          app-private-key: ${{ secrets.SOHYOL_APP_PRIVATE_KEY }}
